language: php
sudo: required
dist: trusty
group: edge
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm # on Trusty only
  - nightly
  - hhvm-3.3
  - hhvm-3.6
  - hhvm-3.9
  - hhvm-3.12
  - hhvm-3.15
  - hhvm-3.18
  - hhvm-nightly
script: 
    phpunit tests/sqlformongoTest.php
# configure notifications (email, IRC, campfire etc)
notifications:
  email: "aaaaa976@gmail.com"