<?php
/**
 * SQLForMongodb.php
 *
 * Translate SQL queries to MongoDB
 *
 * PHP version 5
 *
 * LICENSE:
 * Copyright (c) 2017 Pedro Pelaez
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 * 3. The name of the author may not be used to endorse or promote products
 *    derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
 * IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 * THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * @author    Pedro Pelaez <aaaaa976@gmail.com>
 * @copyright 2017 Pedro Pelaez
 * @license   http://www.debian.org/misc/bsd.license  BSD License (3 Clause)
 * @version   SVN: $Id$
 * 
 * MongoDB online shell to test results: https://docs.mongodb.com/manual/tutorial/insert-documents/
 */

namespace pedropelaez;

require_once dirname(__FILE__) . '/../vendor/autoload.php';
require_once dirname(__FILE__) . '/../SQLForMongodb.php';

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-07-05 at 19:20:56.
 */
class sqlForMongoTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var sqlForMongo
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SQLForMongodb;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers pedropelaez\sqlForMongo::parse
     */
    public function testParseUnknowed() {
        $this->expectException(\Exception::class);
        SQLForMongodb::parse('NULL');
    }
    
    /**
     * @link https://docs.mongodb.com/manual/reference/sql-comparison/
     * 
     * @covers pedropelaez\sqlForMongo::parse
     * @todo   Implement testParse().
     */
    public function testParseQuery() {
        $tests = 'query_tests.json';
        if (!is_file($tests)) {
            $tests = 'tests/query_tests.json';
        }
        $tests = json_decode(file_get_contents($tests));
        foreach($tests as $test) {
            $mongo = SQLForMongodb::parse($test->sql);
            $this->assertEquals($test->mongodb, $mongo, 'Fail parsing "'.$test->sql.'"');
        }
    }

}
